### ISSUE TITLE
Error while selecting "Get all repositories" option

### ISSUE THREAD

**Issue by NiniiGit** [floe/github-bulk-editor#1]
Hi ,

I tried to use the tool created by you by referring to your read.md (as I am working on the same task as you to transfer repo from one org to another) . When I executed script by supplying my account details (login and password at line 10) , I am getting below error. Is there any changes in this code that I should be aware of to use it?

**python3 github-bulk-editor.py 
Get all repositories https://api.github.com/user/repos full_name
Traceback (most recent call last):
  File "github-bulk-editor.py", line 138, in on_source_activate
    self.liststore.append([False,"",item[field],item["id"]])
TypeError: string indices must be integers**

**Comment by LanHao0** [comment]
same problem

**Comment by floe** [comment]
Quoting from the `README`: "To use it, you need to add your own account and password or API key in line 10 (https://github.com/floe/github-bulk-editor/blob/master/github-bulk-editor.py#L10)." I guess I'll add a more descriptive error message, though.

**Comment by floe** [comment]
Addendum: IIRC it's no longer sufficient to just paste in your own credentials, you need to generate an access token: https://github.com/settings/tokens
